// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCqURMUrlyfqqJuL1o1kuJxl5Vj4A9Hak',
    appId: '1:1051430206062:android:aab281cb2ea1816b21c47f',
    messagingSenderId: '1051430206062',
    projectId: 'project-e82fa8f3-3868-42a9-a35',
    storageBucket: 'project-e82fa8f3-3868-42a9-a35.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW5mIVNn4p5etMXAkpcRmrFlm8uTfDl04',
    appId: '1:1051430206062:web:e9b02b11f1bf1ab221c47f',
    messagingSenderId: '1051430206062',
    projectId: 'project-e82fa8f3-3868-42a9-a35',
    authDomain: 'project-e82fa8f3-3868-42a9-a35.firebaseapp.com',
    storageBucket: 'project-e82fa8f3-3868-42a9-a35.firebasestorage.app',
    measurementId: 'G-JR1FJPQ2YM',
  );
}
